# $Id: //depot/sw/releases/7.3_AP/linux/kernels/mips-linux-2.6.15/arch/m68k/sun3/prom/Makefile#1 $
# Makefile for the Sun Boot PROM interface library under
# Linux.
#

obj-y := init.o console.o printf.o  misc.o
#bootstr.o init.o misc.o segment.o console.o printf.o
