# $Id: //depot/sw/releases/7.3_AP/linux/kernels/mips-linux-2.6.15/drivers/net/wireless/prism54/Makefile#1 $

prism54-objs := islpci_eth.o islpci_mgt.o \
                isl_38xx.o isl_ioctl.o islpci_dev.o \
		islpci_hotplug.o oid_mgt.o

obj-$(CONFIG_PRISM54) += prism54.o

