/*
 * Automatically generated C config: don't edit
 * Linux kernel version: 2.6.15-5.2
 * Mon Aug 20 12:11:43 2012
 */
#define AUTOCONF_INCLUDED
#define CONFIG_MIPS 1

/*
 * Machine selection
 */
#undef CONFIG_MIPS_MTX1
#undef CONFIG_MIPS_BOSPORUS
#undef CONFIG_MIPS_PB1000
#undef CONFIG_MIPS_PB1100
#undef CONFIG_MIPS_PB1500
#undef CONFIG_MIPS_PB1550
#undef CONFIG_MIPS_PB1200
#undef CONFIG_MIPS_DB1000
#undef CONFIG_MIPS_DB1100
#undef CONFIG_MIPS_DB1500
#undef CONFIG_MIPS_DB1550
#undef CONFIG_MIPS_DB1200
#undef CONFIG_MIPS_MIRAGE
#undef CONFIG_MIPS_COBALT
#undef CONFIG_MACH_DECSTATION
#undef CONFIG_MIPS_EV64120
#undef CONFIG_MIPS_EV96100
#undef CONFIG_MIPS_IVR
#undef CONFIG_MIPS_ITE8172
#undef CONFIG_MACH_JAZZ
#undef CONFIG_LASAT
#undef CONFIG_MIPS_ATLAS
#undef CONFIG_MIPS_MALTA
#undef CONFIG_MIPS_SEAD
#undef CONFIG_MIPS_SIM
#undef CONFIG_MOMENCO_JAGUAR_ATX
#undef CONFIG_MOMENCO_OCELOT
#undef CONFIG_MOMENCO_OCELOT_3
#undef CONFIG_MOMENCO_OCELOT_C
#undef CONFIG_MOMENCO_OCELOT_G
#undef CONFIG_MIPS_XXS1500
#undef CONFIG_PNX8550_V2PCI
#undef CONFIG_PNX8550_JBS
#undef CONFIG_DDB5074
#undef CONFIG_DDB5476
#undef CONFIG_DDB5477
#undef CONFIG_MACH_VR41XX
#undef CONFIG_PMC_YOSEMITE
#undef CONFIG_QEMU
#define CONFIG_SGI_IP22 1
#undef CONFIG_SGI_IP27
#undef CONFIG_SGI_IP32
#undef CONFIG_SIBYTE_BIGSUR
#undef CONFIG_SIBYTE_SWARM
#undef CONFIG_SIBYTE_SENTOSA
#undef CONFIG_SIBYTE_RHONE
#undef CONFIG_SIBYTE_CARMEL
#undef CONFIG_SIBYTE_PTSWARM
#undef CONFIG_SIBYTE_LITTLESUR
#undef CONFIG_SIBYTE_CRHINE
#undef CONFIG_SIBYTE_CRHONE
#undef CONFIG_SNI_RM200_PCI
#undef CONFIG_TOSHIBA_JMR3927
#undef CONFIG_TOSHIBA_RBTX4927
#undef CONFIG_TOSHIBA_RBTX4938
#undef CONFIG_MACH_AR7100
#undef CONFIG_MACH_AR7240
#define CONFIG_RWSEM_GENERIC_SPINLOCK 1
#define CONFIG_GENERIC_CALIBRATE_DELAY 1
#define CONFIG_ARC 1
#define CONFIG_DMA_NONCOHERENT 1
#define CONFIG_DMA_NEED_PCI_MAP_STATE 1
#define CONFIG_CPU_BIG_ENDIAN 1
#undef CONFIG_CPU_LITTLE_ENDIAN
#define CONFIG_SYS_SUPPORTS_BIG_ENDIAN 1
#define CONFIG_IRQ_CPU 1
#define CONFIG_SWAP_IO_SPACE 1
#define CONFIG_ARC32 1
#define CONFIG_BOOT_ELF32 1
#define CONFIG_MIPS_L1_CACHE_SHIFT 5
#undef CONFIG_ARC_CONSOLE
#define CONFIG_ARC_PROMLIB 1

/*
 * CPU selection
 */
#undef CONFIG_CPU_MIPS32_R1
#undef CONFIG_CPU_MIPS32_R2
#undef CONFIG_CPU_MIPS64_R1
#undef CONFIG_CPU_MIPS64_R2
#undef CONFIG_CPU_R3000
#undef CONFIG_CPU_TX39XX
#undef CONFIG_CPU_VR41XX
#undef CONFIG_CPU_R4300
#define CONFIG_CPU_R4X00 1
#undef CONFIG_CPU_TX49XX
#undef CONFIG_CPU_R5000
#undef CONFIG_CPU_R5432
#undef CONFIG_CPU_R6000
#undef CONFIG_CPU_NEVADA
#undef CONFIG_CPU_R8000
#undef CONFIG_CPU_R10000
#undef CONFIG_CPU_RM7000
#undef CONFIG_CPU_RM9000
#undef CONFIG_CPU_SB1
#define CONFIG_SYS_HAS_CPU_R4X00 1
#define CONFIG_SYS_HAS_CPU_R5000 1
#define CONFIG_SYS_SUPPORTS_32BIT_KERNEL 1
#define CONFIG_SYS_SUPPORTS_64BIT_KERNEL 1
#define CONFIG_CPU_SUPPORTS_32BIT_KERNEL 1
#define CONFIG_CPU_SUPPORTS_64BIT_KERNEL 1

/*
 * Kernel type
 */
#define CONFIG_32BIT 1
#undef CONFIG_64BIT
#define CONFIG_PAGE_SIZE_4KB 1
#undef CONFIG_PAGE_SIZE_8KB
#undef CONFIG_PAGE_SIZE_16KB
#undef CONFIG_PAGE_SIZE_64KB
#define CONFIG_BOARD_SCACHE 1
#define CONFIG_IP22_CPU_SCACHE 1
#undef CONFIG_MIPS_MT
#undef CONFIG_64BIT_PHYS_ADDR
#undef CONFIG_CPU_ADVANCED
#define CONFIG_CPU_HAS_LLSC 1
#define CONFIG_CPU_HAS_SYNC 1
#define CONFIG_GENERIC_HARDIRQS 1
#define CONFIG_GENERIC_IRQ_PROBE 1
#define CONFIG_ARCH_FLATMEM_ENABLE 1
#define CONFIG_SELECT_MEMORY_MODEL 1
#define CONFIG_FLATMEM_MANUAL 1
#undef CONFIG_DISCONTIGMEM_MANUAL
#undef CONFIG_SPARSEMEM_MANUAL
#define CONFIG_FLATMEM 1
#define CONFIG_FLAT_NODE_MEM_MAP 1
#undef CONFIG_SPARSEMEM_STATIC
#define CONFIG_SPLIT_PTLOCK_CPUS 4
#undef CONFIG_PREEMPT_NONE
#define CONFIG_PREEMPT_VOLUNTARY 1
#undef CONFIG_PREEMPT

/*
 * Code maturity level options
 */
#define CONFIG_EXPERIMENTAL 1
#define CONFIG_CLEAN_COMPILE 1
#define CONFIG_BROKEN_ON_SMP 1
#define CONFIG_INIT_ENV_ARG_LIMIT 32

/*
 * General setup
 */
#define CONFIG_LOCALVERSION ""
#undef CONFIG_LOCALVERSION_AUTO
#define CONFIG_SWAP 1
#define CONFIG_SYSVIPC 1
#define CONFIG_POSIX_MQUEUE 1
#define CONFIG_BSD_PROCESS_ACCT 1
#define CONFIG_BSD_PROCESS_ACCT_V3 1
#define CONFIG_SYSCTL 1
#define CONFIG_AUDIT 1
#define CONFIG_HOTPLUG 1
#define CONFIG_KOBJECT_UEVENT 1
#undef CONFIG_IKCONFIG
#define CONFIG_INITRAMFS_SOURCE ""
#undef CONFIG_CC_OPTIMIZE_FOR_SIZE
#define CONFIG_EMBEDDED 1
#define CONFIG_KALLSYMS 1
#define CONFIG_KALLSYMS_ALL 1
#undef CONFIG_KALLSYMS_EXTRA_PASS
#define CONFIG_PRINTK 1
#define CONFIG_BUG 1
#define CONFIG_BASE_FULL 1
#undef CONFIG_KMALLOC_ACCOUNTING
#define CONFIG_FUTEX 1
#define CONFIG_EPOLL 1
#define CONFIG_SHMEM 1
#define CONFIG_CC_ALIGN_FUNCTIONS 0
#define CONFIG_CC_ALIGN_LABELS 0
#define CONFIG_CC_ALIGN_LOOPS 0
#define CONFIG_CC_ALIGN_JUMPS 0
#undef CONFIG_TINY_SHMEM
#define CONFIG_BASE_SMALL 0

/*
 * Loadable module support
 */
#define CONFIG_MODULES 1
#define CONFIG_MODULE_UNLOAD 1
#undef CONFIG_MODULE_FORCE_UNLOAD
#define CONFIG_OBSOLETE_MODPARM 1
#define CONFIG_MODVERSIONS 1
#define CONFIG_MODULE_SRCVERSION_ALL 1
#undef CONFIG_KMOD

/*
 * Block layer
 */
#undef CONFIG_LBD

/*
 * IO Schedulers
 */
#define CONFIG_IOSCHED_NOOP 1
#define CONFIG_IOSCHED_AS 1
#define CONFIG_IOSCHED_DEADLINE 1
#define CONFIG_IOSCHED_CFQ 1
#undef CONFIG_DEFAULT_AS
#undef CONFIG_DEFAULT_DEADLINE
#define CONFIG_DEFAULT_CFQ 1
#undef CONFIG_DEFAULT_NOOP
#define CONFIG_DEFAULT_IOSCHED "cfq"

/*
 * Bus options (PCI, PCMCIA, EISA, ISA, TC)
 */
#define CONFIG_HW_HAS_EISA 1
#define CONFIG_ISA 1
#define CONFIG_EISA 1
#define CONFIG_EISA_NAMES 1
#define CONFIG_MMU 1

/*
 * PCCARD (PCMCIA/CardBus) support
 */
#define CONFIG_PCCARD_MODULE 1
#undef CONFIG_PCMCIA_DEBUG
#define CONFIG_PCMCIA_MODULE 1
#define CONFIG_PCMCIA_LOAD_CIS 1
#define CONFIG_PCMCIA_IOCTL 1

/*
 * PC-card bridges
 */
#define CONFIG_I82365_MODULE 1
#define CONFIG_TCIC_MODULE 1
#define CONFIG_PCMCIA_PROBE 1
#define CONFIG_PCCARD_NONSTATIC_MODULE 1

/*
 * PCI Hotplug Support
 */

/*
 * Executable file formats
 */
#define CONFIG_BINFMT_ELF 1
#define CONFIG_BINFMT_MISC_MODULE 1
#define CONFIG_TRAD_SIGNALS 1

/*
 * Networking
 */
#define CONFIG_NET 1

/*
 * Networking options
 */
#define CONFIG_PACKET 1
#define CONFIG_PACKET_MMAP 1
#define CONFIG_UNIX 1
#define CONFIG_XFRM 1
#define CONFIG_XFRM_USER_MODULE 1
#define CONFIG_NET_KEY_MODULE 1
#define CONFIG_INET 1
#define CONFIG_IP_MULTICAST 1
#define CONFIG_IP_ADVANCED_ROUTER 1
#define CONFIG_ASK_IP_FIB_HASH 1
#undef CONFIG_IP_FIB_TRIE
#define CONFIG_IP_FIB_HASH 1
#define CONFIG_IP_MULTIPLE_TABLES 1
#undef CONFIG_IP_ROUTE_FWMARK
#define CONFIG_IP_ROUTE_MULTIPATH 1
#undef CONFIG_IP_ROUTE_MULTIPATH_CACHED
#define CONFIG_IP_ROUTE_VERBOSE 1
#undef CONFIG_IP_PNP
#define CONFIG_NET_IPIP_MODULE 1
#define CONFIG_NET_IPGRE_MODULE 1
#define CONFIG_NET_IPGRE_BROADCAST 1
#define CONFIG_IP_MROUTE 1
#define CONFIG_IP_PIMSM_V1 1
#define CONFIG_IP_PIMSM_V2 1
#undef CONFIG_ARPD
#define CONFIG_SYN_COOKIES 1
#define CONFIG_INET_AH_MODULE 1
#define CONFIG_INET_ESP_MODULE 1
#define CONFIG_INET_IPCOMP_MODULE 1
#define CONFIG_INET_TUNNEL_MODULE 1
#define CONFIG_INET_DIAG 1
#define CONFIG_INET_TCP_DIAG 1
#define CONFIG_TCP_CONG_ADVANCED 1

/*
 * TCP congestion control
 */
#define CONFIG_TCP_CONG_BIC_MODULE 1
#define CONFIG_TCP_CONG_WESTWOOD_MODULE 1
#define CONFIG_TCP_CONG_HTCP_MODULE 1
#define CONFIG_TCP_CONG_HSTCP_MODULE 1
#define CONFIG_TCP_CONG_HYBLA_MODULE 1
#define CONFIG_TCP_CONG_VEGAS_MODULE 1
#define CONFIG_TCP_CONG_SCALABLE_MODULE 1

/*
 * IP: Virtual Server Configuration
 */
#define CONFIG_IP_VS_MODULE 1
#undef CONFIG_IP_VS_DEBUG
#define CONFIG_IP_VS_TAB_BITS 12

/*
 * IPVS transport protocol load balancing support
 */
#define CONFIG_IP_VS_PROTO_TCP 1
#define CONFIG_IP_VS_PROTO_UDP 1
#define CONFIG_IP_VS_PROTO_ESP 1
#define CONFIG_IP_VS_PROTO_AH 1

/*
 * IPVS scheduler
 */
#define CONFIG_IP_VS_RR_MODULE 1
#define CONFIG_IP_VS_WRR_MODULE 1
#define CONFIG_IP_VS_LC_MODULE 1
#define CONFIG_IP_VS_WLC_MODULE 1
#define CONFIG_IP_VS_LBLC_MODULE 1
#define CONFIG_IP_VS_LBLCR_MODULE 1
#define CONFIG_IP_VS_DH_MODULE 1
#define CONFIG_IP_VS_SH_MODULE 1
#define CONFIG_IP_VS_SED_MODULE 1
#define CONFIG_IP_VS_NQ_MODULE 1

/*
 * IPVS application helper
 */
#define CONFIG_IP_VS_FTP_MODULE 1
#define CONFIG_IPV6 1
#define CONFIG_IPV6_PRIVACY 1
#define CONFIG_INET6_AH_MODULE 1
#define CONFIG_INET6_ESP_MODULE 1
#define CONFIG_INET6_IPCOMP_MODULE 1
#define CONFIG_INET6_TUNNEL_MODULE 1
#define CONFIG_IPV6_TUNNEL_MODULE 1
#define CONFIG_NETFILTER 1
#undef CONFIG_NETFILTER_DEBUG
#define CONFIG_BRIDGE_NETFILTER 1

/*
 * Core Netfilter Configuration
 */
#define CONFIG_NETFILTER_NETLINK_MODULE 1
#define CONFIG_NETFILTER_NETLINK_QUEUE_MODULE 1
#define CONFIG_NETFILTER_NETLINK_LOG_MODULE 1
#define CONFIG_NF_CONNTRACK_MODULE 1
#define CONFIG_NF_CT_ACCT 1
#define CONFIG_NF_CONNTRACK_MARK 1
#define CONFIG_NF_CONNTRACK_EVENTS 1
#define CONFIG_NF_CT_PROTO_SCTP_MODULE 1
#define CONFIG_NF_CONNTRACK_FTP_MODULE 1

/*
 * IP: Netfilter Configuration
 */
#define CONFIG_NF_CONNTRACK_IPV4_MODULE 1
#undef CONFIG_IP_NF_CONNTRACK
#define CONFIG_IP_NF_QUEUE_MODULE 1
#define CONFIG_IP_NF_IPTABLES_MODULE 1
#undef CONFIG_IP_NF_MATCH_LIMIT
#undef CONFIG_IP_NF_MATCH_IPRANGE
#undef CONFIG_IP_NF_MATCH_MAC
#undef CONFIG_IP_NF_MATCH_PKTTYPE
#undef CONFIG_IP_NF_MATCH_MARK
#undef CONFIG_IP_NF_MATCH_MULTIPORT
#undef CONFIG_IP_NF_MATCH_TOS
#undef CONFIG_IP_NF_MATCH_RECENT
#define CONFIG_IP_NF_MATCH_ECN_MODULE 1
#undef CONFIG_IP_NF_MATCH_DSCP
#undef CONFIG_IP_NF_MATCH_AH_ESP
#undef CONFIG_IP_NF_MATCH_LENGTH
#define CONFIG_IP_NF_MATCH_TTL_MODULE 1
#undef CONFIG_IP_NF_MATCH_TCPMSS
#undef CONFIG_IP_NF_MATCH_HELPER
#undef CONFIG_IP_NF_MATCH_STATE
#undef CONFIG_IP_NF_MATCH_CONNTRACK
#undef CONFIG_IP_NF_MATCH_OWNER
#undef CONFIG_IP_NF_MATCH_PHYSDEV
#define CONFIG_IP_NF_MATCH_ADDRTYPE_MODULE 1
#undef CONFIG_IP_NF_MATCH_REALM
#undef CONFIG_IP_NF_MATCH_SCTP
#undef CONFIG_IP_NF_MATCH_DCCP
#undef CONFIG_IP_NF_MATCH_COMMENT
#undef CONFIG_IP_NF_MATCH_CONNMARK
#undef CONFIG_IP_NF_MATCH_CONNBYTES
#undef CONFIG_IP_NF_MATCH_HASHLIMIT
#undef CONFIG_IP_NF_MATCH_STRING
#define CONFIG_IP_NF_FILTER_MODULE 1
#define CONFIG_IP_NF_TARGET_REJECT_MODULE 1
#define CONFIG_IP_NF_TARGET_LOG_MODULE 1
#define CONFIG_IP_NF_TARGET_ULOG_MODULE 1
#undef CONFIG_IP_NF_TARGET_TCPMSS
#undef CONFIG_IP_NF_TARGET_NFQUEUE
#define CONFIG_IP_NF_MANGLE_MODULE 1
#undef CONFIG_IP_NF_TARGET_TOS
#define CONFIG_IP_NF_TARGET_ECN_MODULE 1
#undef CONFIG_IP_NF_TARGET_DSCP
#undef CONFIG_IP_NF_TARGET_MARK
#undef CONFIG_IP_NF_TARGET_CLASSIFY
#define CONFIG_IP_NF_TARGET_TTL_MODULE 1
#undef CONFIG_IP_NF_TARGET_CONNMARK
#define CONFIG_IP_NF_TARGET_CLUSTERIP_MODULE 1
#define CONFIG_IP_NF_RAW_MODULE 1
#undef CONFIG_IP_NF_TARGET_NOTRACK
#undef CONFIG_IP_NF_HIPAC
#define CONFIG_IP_NF_ARPTABLES_MODULE 1
#define CONFIG_IP_NF_ARPFILTER_MODULE 1
#define CONFIG_IP_NF_ARP_MANGLE_MODULE 1

/*
 * IPv6: Netfilter Configuration (EXPERIMENTAL)
 */
#define CONFIG_NF_CONNTRACK_IPV6_MODULE 1
#define CONFIG_IP6_NF_QUEUE_MODULE 1
#define CONFIG_IP6_NF_IPTABLES_MODULE 1
#undef CONFIG_IP6_NF_MATCH_LIMIT
#undef CONFIG_IP6_NF_MATCH_MAC
#define CONFIG_IP6_NF_MATCH_RT_MODULE 1
#define CONFIG_IP6_NF_MATCH_OPTS_MODULE 1
#define CONFIG_IP6_NF_MATCH_FRAG_MODULE 1
#define CONFIG_IP6_NF_MATCH_HL_MODULE 1
#undef CONFIG_IP6_NF_MATCH_MULTIPORT
#undef CONFIG_IP6_NF_MATCH_OWNER
#undef CONFIG_IP6_NF_MATCH_MARK
#define CONFIG_IP6_NF_MATCH_IPV6HEADER_MODULE 1
#undef CONFIG_IP6_NF_MATCH_AHESP
#undef CONFIG_IP6_NF_MATCH_LENGTH
#define CONFIG_IP6_NF_MATCH_EUI64_MODULE 1
#undef CONFIG_IP6_NF_MATCH_PHYSDEV
#define CONFIG_IP6_NF_FILTER_MODULE 1
#define CONFIG_IP6_NF_TARGET_LOG_MODULE 1
#define CONFIG_IP6_NF_TARGET_REJECT_MODULE 1
#undef CONFIG_IP6_NF_TARGET_NFQUEUE
#define CONFIG_IP6_NF_MANGLE_MODULE 1
#undef CONFIG_IP6_NF_TARGET_MARK
#define CONFIG_IP6_NF_TARGET_HL_MODULE 1
#define CONFIG_IP6_NF_RAW_MODULE 1

/*
 * DECnet: Netfilter Configuration
 */
#define CONFIG_DECNET_NF_GRABULATOR_MODULE 1

/*
 * Bridge: Netfilter Configuration
 */
#define CONFIG_BRIDGE_NF_EBTABLES_MODULE 1
#define CONFIG_BRIDGE_EBT_BROUTE_MODULE 1
#define CONFIG_BRIDGE_EBT_T_FILTER_MODULE 1
#define CONFIG_BRIDGE_EBT_T_NAT_MODULE 1
#define CONFIG_BRIDGE_EBT_802_3_MODULE 1
#define CONFIG_BRIDGE_EBT_AMONG_MODULE 1
#define CONFIG_BRIDGE_EBT_ARP_MODULE 1
#define CONFIG_BRIDGE_EBT_IP_MODULE 1
#define CONFIG_BRIDGE_EBT_LIMIT_MODULE 1
#define CONFIG_BRIDGE_EBT_MARK_MODULE 1
#define CONFIG_BRIDGE_EBT_PKTTYPE_MODULE 1
#define CONFIG_BRIDGE_EBT_STP_MODULE 1
#define CONFIG_BRIDGE_EBT_VLAN_MODULE 1
#define CONFIG_BRIDGE_EBT_ARPREPLY_MODULE 1
#define CONFIG_BRIDGE_EBT_DNAT_MODULE 1
#define CONFIG_BRIDGE_EBT_MARK_T_MODULE 1
#define CONFIG_BRIDGE_EBT_REDIRECT_MODULE 1
#define CONFIG_BRIDGE_EBT_SNAT_MODULE 1
#define CONFIG_BRIDGE_EBT_LOG_MODULE 1
#define CONFIG_BRIDGE_EBT_ULOG_MODULE 1
#undef CONFIG_BRIDGE_EBT_ARPNAT

/*
 * DCCP Configuration (EXPERIMENTAL)
 */
#define CONFIG_IP_DCCP_MODULE 1
#define CONFIG_INET_DCCP_DIAG_MODULE 1

/*
 * DCCP CCIDs Configuration (EXPERIMENTAL)
 */
#define CONFIG_IP_DCCP_CCID3_MODULE 1
#define CONFIG_IP_DCCP_TFRC_LIB_MODULE 1

/*
 * DCCP Kernel Hacking
 */
#undef CONFIG_IP_DCCP_DEBUG
#undef CONFIG_IP_DCCP_UNLOAD_HACK

/*
 * SCTP Configuration (EXPERIMENTAL)
 */
#define CONFIG_IP_SCTP_MODULE 1
#undef CONFIG_SCTP_DBG_MSG
#undef CONFIG_SCTP_DBG_OBJCNT
#undef CONFIG_SCTP_HMAC_NONE
#undef CONFIG_SCTP_HMAC_SHA1
#define CONFIG_SCTP_HMAC_MD5 1
#define CONFIG_ATM_MODULE 1
#define CONFIG_ATM_CLIP_MODULE 1
#undef CONFIG_ATM_CLIP_NO_ICMP
#define CONFIG_ATM_LANE_MODULE 1
#define CONFIG_ATM_MPOA_MODULE 1
#define CONFIG_ATM_BR2684_MODULE 1
#undef CONFIG_ATM_BR2684_IPFILTER
#define CONFIG_BRIDGE_MODULE 1
#define CONFIG_VLAN_8021Q_MODULE 1
#define CONFIG_DECNET_MODULE 1
#undef CONFIG_DECNET_ROUTER
#define CONFIG_LLC 1
#define CONFIG_LLC2_MODULE 1
#define CONFIG_IPX_MODULE 1
#undef CONFIG_IPX_INTERN
#define CONFIG_ATALK_MODULE 1
#undef CONFIG_DEV_APPLETALK
#define CONFIG_X25_MODULE 1
#define CONFIG_LAPB_MODULE 1
#undef CONFIG_NET_DIVERT
#define CONFIG_ECONET_MODULE 1
#define CONFIG_ECONET_AUNUDP 1
#define CONFIG_ECONET_NATIVE 1
#define CONFIG_WAN_ROUTER_MODULE 1

/*
 * QoS and/or fair queueing
 */
#define CONFIG_NET_SCHED 1
#define CONFIG_NET_SCH_CLK_JIFFIES 1
#undef CONFIG_NET_SCH_CLK_GETTIMEOFDAY
#undef CONFIG_NET_SCH_CLK_CPU

/*
 * Queueing/Scheduling
 */
#define CONFIG_NET_SCH_CBQ_MODULE 1
#define CONFIG_NET_SCH_HTB_MODULE 1
#define CONFIG_NET_SCH_HFSC_MODULE 1
#define CONFIG_NET_SCH_ATM_MODULE 1
#define CONFIG_NET_SCH_PRIO_MODULE 1
#define CONFIG_NET_SCH_RED_MODULE 1
#define CONFIG_NET_SCH_SFQ_MODULE 1
#define CONFIG_NET_SCH_TEQL_MODULE 1
#define CONFIG_NET_SCH_TBF_MODULE 1
#define CONFIG_NET_SCH_GRED_MODULE 1
#define CONFIG_NET_SCH_DSMARK_MODULE 1
#define CONFIG_NET_SCH_NETEM_MODULE 1
#define CONFIG_NET_SCH_INGRESS_MODULE 1

/*
 * Classification
 */
#define CONFIG_NET_CLS 1
#define CONFIG_NET_CLS_BASIC_MODULE 1
#define CONFIG_NET_CLS_TCINDEX_MODULE 1
#define CONFIG_NET_CLS_ROUTE4_MODULE 1
#define CONFIG_NET_CLS_ROUTE 1
#define CONFIG_NET_CLS_FW_MODULE 1
#define CONFIG_NET_CLS_U32_MODULE 1
#undef CONFIG_CLS_U32_PERF
#define CONFIG_CLS_U32_MARK 1
#define CONFIG_NET_CLS_RSVP_MODULE 1
#define CONFIG_NET_CLS_RSVP6_MODULE 1
#define CONFIG_NET_EMATCH 1
#define CONFIG_NET_EMATCH_STACK 32
#define CONFIG_NET_EMATCH_CMP_MODULE 1
#define CONFIG_NET_EMATCH_NBYTE_MODULE 1
#define CONFIG_NET_EMATCH_U32_MODULE 1
#define CONFIG_NET_EMATCH_META_MODULE 1
#define CONFIG_NET_EMATCH_TEXT_MODULE 1
#define CONFIG_NET_CLS_ACT 1
#define CONFIG_NET_ACT_POLICE_MODULE 1
#define CONFIG_NET_ACT_GACT_MODULE 1
#define CONFIG_GACT_PROB 1
#define CONFIG_NET_ACT_MIRRED_MODULE 1
#define CONFIG_NET_ACT_IPT_MODULE 1
#define CONFIG_NET_ACT_PEDIT_MODULE 1
#define CONFIG_NET_ACT_SIMP_MODULE 1
#undef CONFIG_NET_CLS_IND
#define CONFIG_NET_ESTIMATOR 1

/*
 * Network testing
 */
#define CONFIG_NET_PKTGEN_MODULE 1
#define CONFIG_HAMRADIO 1

/*
 * Packet Radio protocols
 */
#define CONFIG_AX25_MODULE 1
#define CONFIG_AX25_DAMA_SLAVE 1
#define CONFIG_NETROM_MODULE 1
#define CONFIG_ROSE_MODULE 1

/*
 * AX.25 network device drivers
 */
#define CONFIG_MKISS_MODULE 1
#define CONFIG_6PACK_MODULE 1
#define CONFIG_BPQETHER_MODULE 1
#define CONFIG_BAYCOM_SER_FDX_MODULE 1
#define CONFIG_BAYCOM_SER_HDX_MODULE 1
#define CONFIG_BAYCOM_PAR_MODULE 1
#define CONFIG_BAYCOM_EPP_MODULE 1
#define CONFIG_YAM_MODULE 1
#define CONFIG_IRDA_MODULE 1

/*
 * IrDA protocols
 */
#define CONFIG_IRLAN_MODULE 1
#define CONFIG_IRNET_MODULE 1
#define CONFIG_IRCOMM_MODULE 1
#define CONFIG_IRDA_ULTRA 1

/*
 * IrDA options
 */
#define CONFIG_IRDA_CACHE_LAST_LSAP 1
#define CONFIG_IRDA_FAST_RR 1
#define CONFIG_IRDA_DEBUG 1

/*
 * Infrared-port device drivers
 */

/*
 * SIR device drivers
 */
#define CONFIG_IRTTY_SIR_MODULE 1

/*
 * Dongle support
 */
#define CONFIG_DONGLE 1
#define CONFIG_ESI_DONGLE_MODULE 1
#define CONFIG_ACTISYS_DONGLE_MODULE 1
#define CONFIG_TEKRAM_DONGLE_MODULE 1
#define CONFIG_LITELINK_DONGLE_MODULE 1
#define CONFIG_MA600_DONGLE_MODULE 1
#define CONFIG_GIRBIL_DONGLE_MODULE 1
#define CONFIG_MCP2120_DONGLE_MODULE 1
#define CONFIG_OLD_BELKIN_DONGLE_MODULE 1
#define CONFIG_ACT200L_DONGLE_MODULE 1

/*
 * Old SIR device drivers
 */
#undef CONFIG_IRPORT_SIR

/*
 * Old Serial dongle support
 */

/*
 * FIR device drivers
 */
#define CONFIG_BT_MODULE 1
#define CONFIG_BT_L2CAP_MODULE 1
#define CONFIG_BT_SCO_MODULE 1
#define CONFIG_BT_RFCOMM_MODULE 1
#define CONFIG_BT_RFCOMM_TTY 1
#define CONFIG_BT_BNEP_MODULE 1
#define CONFIG_BT_BNEP_MC_FILTER 1
#define CONFIG_BT_BNEP_PROTO_FILTER 1
#define CONFIG_BT_CMTP_MODULE 1
#define CONFIG_BT_HIDP_MODULE 1

/*
 * Bluetooth device drivers
 */
#define CONFIG_BT_HCIUART_MODULE 1
#define CONFIG_BT_HCIUART_H4 1
#define CONFIG_BT_HCIUART_BCSP 1
#define CONFIG_BT_HCIDTL1_MODULE 1
#define CONFIG_BT_HCIBT3C_MODULE 1
#define CONFIG_BT_HCIBLUECARD_MODULE 1
#define CONFIG_BT_HCIBTUART_MODULE 1
#define CONFIG_BT_HCIVHCI_MODULE 1
#undef CONFIG_IEEE80211

/*
 * Device Drivers
 */

/*
 * Generic Driver Options
 */
#undef CONFIG_STANDALONE
#define CONFIG_PREVENT_FIRMWARE_BUILD 1
#define CONFIG_FW_LOADER 1
#undef CONFIG_DEBUG_DRIVER

/*
 * Connector - unified userspace <-> kernelspace linker
 */
#define CONFIG_CONNECTOR 1
#define CONFIG_PROC_EVENTS 1

/*
 * Memory Technology Devices (MTD)
 */
#define CONFIG_MTD_MODULE 1
#undef CONFIG_MTD_DEBUG
#define CONFIG_MTD_CONCAT_MODULE 1
#define CONFIG_MTD_PARTITIONS 1
#define CONFIG_MTD_REDBOOT_PARTS_MODULE 1
#define CONFIG_MTD_REDBOOT_DIRECTORY_BLOCK -1
#undef CONFIG_MTD_REDBOOT_PARTS_UNALLOCATED
#undef CONFIG_MTD_REDBOOT_PARTS_READONLY
#undef CONFIG_MTD_CMDLINE_PARTS

/*
 * User Modules And Translation Layers
 */
#define CONFIG_MTD_CHAR_MODULE 1
#define CONFIG_MTD_BLOCK_MODULE 1
#define CONFIG_MTD_BLOCK_RO_MODULE 1
#define CONFIG_FTL_MODULE 1
#define CONFIG_NFTL_MODULE 1
#define CONFIG_NFTL_RW 1
#define CONFIG_INFTL_MODULE 1
#define CONFIG_RFD_FTL_MODULE 1

/*
 * RAM/ROM/Flash chip drivers
 */
#define CONFIG_MTD_CFI_MODULE 1
#define CONFIG_MTD_JEDECPROBE_MODULE 1
#define CONFIG_MTD_GEN_PROBE_MODULE 1
#undef CONFIG_MTD_CFI_ADV_OPTIONS
#define CONFIG_MTD_MAP_BANK_WIDTH_1 1
#define CONFIG_MTD_MAP_BANK_WIDTH_2 1
#define CONFIG_MTD_MAP_BANK_WIDTH_4 1
#undef CONFIG_MTD_MAP_BANK_WIDTH_8
#undef CONFIG_MTD_MAP_BANK_WIDTH_16
#undef CONFIG_MTD_MAP_BANK_WIDTH_32
#define CONFIG_MTD_CFI_I1 1
#define CONFIG_MTD_CFI_I2 1
#undef CONFIG_MTD_CFI_I4
#undef CONFIG_MTD_CFI_I8
#define CONFIG_MTD_CFI_INTELEXT_MODULE 1
#define CONFIG_MTD_CFI_AMDSTD_MODULE 1
#define CONFIG_MTD_CFI_AMDSTD_RETRY 0
#define CONFIG_MTD_CFI_STAA_MODULE 1
#define CONFIG_MTD_CFI_UTIL_MODULE 1
#define CONFIG_MTD_RAM_MODULE 1
#define CONFIG_MTD_ROM_MODULE 1
#define CONFIG_MTD_ABSENT_MODULE 1

/*
 * Mapping drivers for chip access
 */
#define CONFIG_MTD_COMPLEX_MAPPINGS 1
#define CONFIG_MTD_PHYSMAP_MODULE 1
#define CONFIG_MTD_PHYSMAP_START 0x8000000
#define CONFIG_MTD_PHYSMAP_LEN 0x4000000
#define CONFIG_MTD_PHYSMAP_BANKWIDTH 2
#undef CONFIG_MTD_CSTM_MIPS_IXX
#define CONFIG_MTD_PLATRAM_MODULE 1

/*
 * Self-contained MTD device drivers
 */
#define CONFIG_MTD_SLRAM_MODULE 1
#define CONFIG_MTD_PHRAM_MODULE 1
#define CONFIG_MTD_MTDRAM_MODULE 1
#define CONFIG_MTDRAM_TOTAL_SIZE 4096
#define CONFIG_MTDRAM_ERASE_SIZE 128
#undef CONFIG_MTD_BLKMTD
#define CONFIG_MTD_BLOCK2MTD_MODULE 1

/*
 * Disk-On-Chip Device Drivers
 */
#define CONFIG_MTD_DOC2000_MODULE 1
#define CONFIG_MTD_DOC2001_MODULE 1
#define CONFIG_MTD_DOC2001PLUS_MODULE 1
#define CONFIG_MTD_DOCPROBE_MODULE 1
#define CONFIG_MTD_DOCECC_MODULE 1
#undef CONFIG_MTD_DOCPROBE_ADVANCED
#define CONFIG_MTD_DOCPROBE_ADDRESS 0x0
#undef CONFIG_MTD_AR7100_SPI_FLASH
#undef CONFIG_MTD_AR9100_PARALLEL_FLASH
#undef CONFIG_MTD_AR7240_SPI_FLASH

/*
 * NAND Flash Device Drivers
 */
#define CONFIG_MTD_NAND_MODULE 1
#undef CONFIG_MTD_NAND_VERIFY_WRITE
#define CONFIG_MTD_NAND_IDS_MODULE 1
#define CONFIG_MTD_NAND_DISKONCHIP_MODULE 1
#undef CONFIG_MTD_NAND_DISKONCHIP_PROBE_ADVANCED
#define CONFIG_MTD_NAND_DISKONCHIP_PROBE_ADDRESS 0x0
#undef CONFIG_MTD_NAND_DISKONCHIP_BBTWRITE
#undef CONFIG_MTD_NAND_NANDSIM

/*
 * OneNAND Flash Device Drivers
 */
#define CONFIG_MTD_ONENAND_MODULE 1
#define CONFIG_MTD_ONENAND_VERIFY_WRITE 1

/*
 * Parallel port support
 */
#define CONFIG_PARPORT_MODULE 1
#define CONFIG_PARPORT_PC_MODULE 1
#define CONFIG_PARPORT_PC_FIFO 1
#undef CONFIG_PARPORT_PC_SUPERIO
#define CONFIG_PARPORT_PC_PCMCIA_MODULE 1
#undef CONFIG_PARPORT_GSC
#define CONFIG_PARPORT_1284 1

/*
 * Plug and Play support
 */
#define CONFIG_PNP 1
#undef CONFIG_PNP_DEBUG

/*
 * Protocols
 */
#define CONFIG_ISAPNP 1

/*
 * Block devices
 */
#define CONFIG_PARIDE_MODULE 1
#define CONFIG_PARIDE_PARPORT_MODULE 1

/*
 * Parallel IDE high-level drivers
 */
#define CONFIG_PARIDE_PD_MODULE 1
#define CONFIG_PARIDE_PCD_MODULE 1
#define CONFIG_PARIDE_PF_MODULE 1
#define CONFIG_PARIDE_PT_MODULE 1
#define CONFIG_PARIDE_PG_MODULE 1

/*
 * Parallel IDE protocol modules
 */
#define CONFIG_PARIDE_ATEN_MODULE 1
#define CONFIG_PARIDE_BPCK_MODULE 1
#define CONFIG_PARIDE_BPCK6_MODULE 1
#define CONFIG_PARIDE_COMM_MODULE 1
#define CONFIG_PARIDE_DSTR_MODULE 1
#define CONFIG_PARIDE_FIT2_MODULE 1
#define CONFIG_PARIDE_FIT3_MODULE 1
#define CONFIG_PARIDE_EPAT_MODULE 1
#undef CONFIG_PARIDE_EPATC8
#define CONFIG_PARIDE_EPIA_MODULE 1
#define CONFIG_PARIDE_FRIQ_MODULE 1
#define CONFIG_PARIDE_FRPW_MODULE 1
#define CONFIG_PARIDE_KBIC_MODULE 1
#define CONFIG_PARIDE_KTTI_MODULE 1
#define CONFIG_PARIDE_ON20_MODULE 1
#define CONFIG_PARIDE_ON26_MODULE 1
#undef CONFIG_BLK_DEV_COW_COMMON
#define CONFIG_BLK_DEV_LOOP 1
#define CONFIG_BLK_DEV_CRYPTOLOOP_MODULE 1
#define CONFIG_BLK_DEV_NBD_MODULE 1
#define CONFIG_BLK_DEV_RAM 1
#define CONFIG_BLK_DEV_RAM_COUNT 16
#define CONFIG_BLK_DEV_RAM_SIZE 65536
#define CONFIG_BLK_DEV_INITRD 1
#define CONFIG_CDROM_PKTCDVD 1
#define CONFIG_CDROM_PKTCDVD_BUFFERS 8
#undef CONFIG_CDROM_PKTCDVD_WCACHE
#define CONFIG_ATA_OVER_ETH_MODULE 1

/*
 * ATA/ATAPI/MFM/RLL support
 */
#undef CONFIG_IDE

/*
 * SCSI device support
 */
#define CONFIG_RAID_ATTRS_MODULE 1
#define CONFIG_SCSI 1
#define CONFIG_SCSI_PROC_FS 1

/*
 * SCSI support type (disk, tape, CD-ROM)
 */
#define CONFIG_BLK_DEV_SD 1
#define CONFIG_CHR_DEV_ST_MODULE 1
#define CONFIG_CHR_DEV_OSST_MODULE 1
#define CONFIG_BLK_DEV_SR 1
#undef CONFIG_BLK_DEV_SR_VENDOR
#define CONFIG_CHR_DEV_SG 1
#define CONFIG_CHR_DEV_SCH_MODULE 1

/*
 * Some SCSI devices (e.g. CD jukebox) support multiple LUNs
 */
#define CONFIG_SCSI_MULTI_LUN 1
#define CONFIG_SCSI_CONSTANTS 1
#define CONFIG_SCSI_LOGGING 1

/*
 * SCSI Transport Attributes
 */
#define CONFIG_SCSI_SPI_ATTRS 1
#define CONFIG_SCSI_FC_ATTRS_MODULE 1
#define CONFIG_SCSI_ISCSI_ATTRS_MODULE 1
#define CONFIG_SCSI_SAS_ATTRS_MODULE 1

/*
 * SCSI low-level drivers
 */
#define CONFIG_ISCSI_TCP_MODULE 1
#undef CONFIG_SGIWD93_SCSI
#define CONFIG_SCSI_AHA152X_MODULE 1
#define CONFIG_SCSI_AHA1740_MODULE 1
#define CONFIG_SCSI_AIC7XXX_MODULE 1
#define CONFIG_AIC7XXX_CMDS_PER_DEVICE 8
#define CONFIG_AIC7XXX_RESET_DELAY_MS 15000
#undef CONFIG_AIC7XXX_PROBE_EISA_VL
#define CONFIG_AIC7XXX_DEBUG_ENABLE 1
#define CONFIG_AIC7XXX_DEBUG_MASK 0
#define CONFIG_AIC7XXX_REG_PRETTY_PRINT 1
#undef CONFIG_SCSI_AIC7XXX_OLD
#define CONFIG_SCSI_IN2000_MODULE 1
#undef CONFIG_SCSI_SATA
#define CONFIG_SCSI_DTC3280_MODULE 1
#define CONFIG_SCSI_FUTURE_DOMAIN_MODULE 1
#define CONFIG_SCSI_GENERIC_NCR5380_MODULE 1
#define CONFIG_SCSI_GENERIC_NCR5380_MMIO_MODULE 1
#define CONFIG_SCSI_GENERIC_NCR53C400 1
#define CONFIG_SCSI_PPA_MODULE 1
#define CONFIG_SCSI_IMM_MODULE 1
#undef CONFIG_SCSI_IZIP_EPP16
#undef CONFIG_SCSI_IZIP_SLOW_CTR
#define CONFIG_SCSI_NCR53C406A_MODULE 1
#define CONFIG_SCSI_PAS16_MODULE 1
#undef CONFIG_SCSI_PSI240I
#define CONFIG_SCSI_QLOGIC_FAS_MODULE 1
#define CONFIG_SCSI_SIM710_MODULE 1
#define CONFIG_53C700_IO_MAPPED 1
#define CONFIG_SCSI_SYM53C416_MODULE 1
#define CONFIG_SCSI_T128_MODULE 1
#define CONFIG_SCSI_DEBUG_MODULE 1

/*
 * PCMCIA SCSI adapter support
 */
#define CONFIG_PCMCIA_AHA152X_MODULE 1
#define CONFIG_PCMCIA_FDOMAIN_MODULE 1
#define CONFIG_PCMCIA_NINJA_SCSI_MODULE 1
#define CONFIG_PCMCIA_QLOGIC_MODULE 1
#define CONFIG_PCMCIA_SYM53C500_MODULE 1

/*
 * Old CD-ROM drivers (not SCSI, not IDE)
 */
#undef CONFIG_CD_NO_IDESCSI

/*
 * Multi-device support (RAID and LVM)
 */
#define CONFIG_MD 1
#define CONFIG_BLK_DEV_MD 1
#define CONFIG_MD_LINEAR_MODULE 1
#define CONFIG_MD_RAID0_MODULE 1
#define CONFIG_MD_RAID1_MODULE 1
#define CONFIG_MD_RAID10_MODULE 1
#undef CONFIG_MD_RAID5
#undef CONFIG_MD_RAID6
#define CONFIG_MD_MULTIPATH_MODULE 1
#define CONFIG_MD_FAULTY_MODULE 1
#define CONFIG_BLK_DEV_DM 1
#define CONFIG_DM_CRYPT_MODULE 1
#define CONFIG_DM_SNAPSHOT 1
#define CONFIG_DM_MIRROR 1
#define CONFIG_DM_ZERO_MODULE 1
#define CONFIG_DM_MULTIPATH 1
#undef CONFIG_DM_MULTIPATH_EMC

/*
 * Fusion MPT device support
 */
#undef CONFIG_FUSION

/*
 * IEEE 1394 (FireWire) support
 */

/*
 * I2O device support
 */

/*
 * Network device support
 */
#define CONFIG_NETDEVICES 1
#define CONFIG_DUMMY_MODULE 1
#define CONFIG_BONDING_MODULE 1
#define CONFIG_EQUALIZER_MODULE 1
#define CONFIG_TUN 1
#define CONFIG_NET_SB1000_MODULE 1

/*
 * ARCnet devices
 */
#define CONFIG_ARCNET_MODULE 1
#define CONFIG_ARCNET_1201_MODULE 1
#define CONFIG_ARCNET_1051_MODULE 1
#define CONFIG_ARCNET_RAW_MODULE 1
#define CONFIG_ARCNET_CAP_MODULE 1
#define CONFIG_ARCNET_COM90xx_MODULE 1
#define CONFIG_ARCNET_COM90xxIO_MODULE 1
#define CONFIG_ARCNET_RIM_I_MODULE 1
#define CONFIG_ARCNET_COM20020_MODULE 1
#define CONFIG_ARCNET_COM20020_ISA_MODULE 1

/*
 * PHY device support
 */
#define CONFIG_PHYLIB 1

/*
 * MII PHY device drivers
 */
#define CONFIG_MARVELL_PHY 1
#define CONFIG_DAVICOM_PHY 1
#define CONFIG_QSEMI_PHY 1
#define CONFIG_LXT_PHY 1
#define CONFIG_CICADA_PHY 1

/*
 * Ethernet (10 or 100Mbit)
 */
#define CONFIG_NET_ETHERNET 1
#define CONFIG_MII_MODULE 1
#define CONFIG_NET_VENDOR_3COM 1
#define CONFIG_EL1_MODULE 1
#define CONFIG_EL2_MODULE 1
#define CONFIG_EL16_MODULE 1
#define CONFIG_EL3_MODULE 1
#define CONFIG_VORTEX_MODULE 1
#define CONFIG_NET_VENDOR_SMC 1
#define CONFIG_WD80x3_MODULE 1
#define CONFIG_ULTRA_MODULE 1
#define CONFIG_ULTRA32_MODULE 1
#define CONFIG_SMC9194_MODULE 1
#define CONFIG_NET_VENDOR_RACAL 1
#undef CONFIG_NI5010
#define CONFIG_NI52_MODULE 1

/*
 * Tulip family network device support
 */
#define CONFIG_NET_TULIP 1
#define CONFIG_DE4X5_MODULE 1
#define CONFIG_AT1700_MODULE 1
#define CONFIG_DEPCA_MODULE 1
#define CONFIG_HP100_MODULE 1
#define CONFIG_NET_ISA 1
#define CONFIG_E2100_MODULE 1
#define CONFIG_EWRK3_MODULE 1
#define CONFIG_EEXPRESS_MODULE 1
#define CONFIG_EEXPRESS_PRO_MODULE 1
#define CONFIG_HPLAN_PLUS_MODULE 1
#define CONFIG_HPLAN_MODULE 1
#define CONFIG_LP486E_MODULE 1
#define CONFIG_ETH16I_MODULE 1
#define CONFIG_NE2000_MODULE 1
#define CONFIG_SEEQ8005_MODULE 1
#define CONFIG_NET_PCI 1
#define CONFIG_AC3200_MODULE 1
#define CONFIG_APRICOT_MODULE 1
#define CONFIG_CS89x0_MODULE 1
#undef CONFIG_DGRS
#define CONFIG_LNE390_MODULE 1
#define CONFIG_NE3210_MODULE 1
#define CONFIG_ES3210_MODULE 1
#define CONFIG_TLAN_MODULE 1
#undef CONFIG_LAN_SAA9730
#define CONFIG_NET_POCKET 1
#define CONFIG_DE600_MODULE 1
#define CONFIG_DE620_MODULE 1
#undef CONFIG_SGISEEQ

/*
 * Ethernet (1000 Mbit)
 */

/*
 * Ethernet (10000 Mbit)
 */

/*
 * Token Ring devices
 */
#define CONFIG_TR 1
#define CONFIG_IBMTR_MODULE 1
#define CONFIG_SMCTR_MODULE 1

/*
 * Wireless LAN (non-hamradio)
 */
#undef CONFIG_NET_RADIO

/*
 * PCMCIA network device support
 */
#define CONFIG_NET_PCMCIA 1
#define CONFIG_PCMCIA_3C589_MODULE 1
#define CONFIG_PCMCIA_3C574_MODULE 1
#define CONFIG_PCMCIA_FMVJ18X_MODULE 1
#define CONFIG_PCMCIA_PCNET_MODULE 1
#define CONFIG_PCMCIA_NMCLAN_MODULE 1
#define CONFIG_PCMCIA_SMC91C92_MODULE 1
#define CONFIG_PCMCIA_XIRC2PS_MODULE 1
#define CONFIG_PCMCIA_AXNET_MODULE 1
#define CONFIG_ARCNET_COM20020_CS_MODULE 1
#define CONFIG_PCMCIA_IBMTR_MODULE 1

/*
 * Wan interfaces
 */
#define CONFIG_WAN 1
#undef CONFIG_SYNCLINK_SYNCPPP
#define CONFIG_HDLC_MODULE 1
#undef CONFIG_HDLC_RAW
#undef CONFIG_HDLC_RAW_ETH
#undef CONFIG_HDLC_CISCO
#undef CONFIG_HDLC_FR
#undef CONFIG_HDLC_PPP
#undef CONFIG_HDLC_X25
#define CONFIG_N2_MODULE 1
#define CONFIG_C101_MODULE 1
#define CONFIG_DLCI_MODULE 1
#define CONFIG_DLCI_COUNT 24
#define CONFIG_DLCI_MAX 8
#define CONFIG_SDLA_MODULE 1
#undef CONFIG_WAN_ROUTER_DRIVERS
#define CONFIG_LAPBETHER_MODULE 1
#define CONFIG_X25_ASY_MODULE 1

/*
 * ATM drivers
 */
#undef CONFIG_ATM_DUMMY
#define CONFIG_ATM_TCP_MODULE 1
#define CONFIG_FDDI 1
#define CONFIG_DEFXX_MODULE 1
#define CONFIG_PLIP_MODULE 1
#define CONFIG_PPP 1
#define CONFIG_PPP_MULTILINK 1
#define CONFIG_PPP_FILTER 1
#define CONFIG_PPP_ASYNC_MODULE 1
#define CONFIG_PPP_SYNC_TTY_MODULE 1
#define CONFIG_PPP_DEFLATE_MODULE 1
#define CONFIG_PPP_BSDCOMP_MODULE 1
#define CONFIG_PPP_MPPE_MODULE 1
#define CONFIG_PPPOE_MODULE 1
#define CONFIG_PPPOATM_MODULE 1
#define CONFIG_SLIP_MODULE 1
#define CONFIG_SLIP_COMPRESSED 1
#define CONFIG_SLIP_SMART 1
#define CONFIG_SLIP_MODE_SLIP6 1
#undef CONFIG_SHAPER
#define CONFIG_NETCONSOLE_MODULE 1
#define CONFIG_NETPOLL 1
#undef CONFIG_NETPOLL_RX
#undef CONFIG_NETPOLL_TRAP
#define CONFIG_NET_POLL_CONTROLLER 1

/*
 * ISDN subsystem
 */
#define CONFIG_ISDN 1

/*
 * Old ISDN4Linux
 */
#define CONFIG_ISDN_I4L_MODULE 1
#define CONFIG_ISDN_PPP 1
#define CONFIG_ISDN_PPP_VJ 1
#define CONFIG_ISDN_MPP 1
#define CONFIG_IPPP_FILTER 1
#define CONFIG_ISDN_PPP_BSDCOMP_MODULE 1
#define CONFIG_ISDN_AUDIO 1
#define CONFIG_ISDN_TTY_FAX 1
#define CONFIG_ISDN_X25 1

/*
 * ISDN feature submodules
 */
#undef CONFIG_ISDN_DRV_LOOP
#define CONFIG_ISDN_DIVERSION_MODULE 1

/*
 * ISDN4Linux hardware drivers
 */

/*
 * Passive cards
 */
#define CONFIG_ISDN_DRV_HISAX_MODULE 1

/*
 * D-channel protocol features
 */
#define CONFIG_HISAX_EURO 1
#define CONFIG_DE_AOC 1
#undef CONFIG_HISAX_NO_SENDCOMPLETE
#undef CONFIG_HISAX_NO_LLC
#undef CONFIG_HISAX_NO_KEYPAD
#define CONFIG_HISAX_1TR6 1
#define CONFIG_HISAX_NI1 1
#define CONFIG_HISAX_MAX_CARDS 8

/*
 * HiSax supported cards
 */
#define CONFIG_HISAX_16_0 1
#define CONFIG_HISAX_16_3 1
#define CONFIG_HISAX_S0BOX 1
#define CONFIG_HISAX_AVM_A1 1
#define CONFIG_HISAX_FRITZPCI 1
#define CONFIG_HISAX_AVM_A1_PCMCIA 1
#define CONFIG_HISAX_ELSA 1
#define CONFIG_HISAX_IX1MICROR2 1
#define CONFIG_HISAX_DIEHLDIVA 1
#define CONFIG_HISAX_ASUSCOM 1
#define CONFIG_HISAX_TELEINT 1
#define CONFIG_HISAX_HFCS 1
#define CONFIG_HISAX_SEDLBAUER 1
#define CONFIG_HISAX_SPORTSTER 1
#define CONFIG_HISAX_MIC 1
#define CONFIG_HISAX_NICCY 1
#define CONFIG_HISAX_ISURF 1
#define CONFIG_HISAX_HSTSAPHIR 1
#define CONFIG_HISAX_GAZEL 1
#define CONFIG_HISAX_HFC_SX 1
#undef CONFIG_HISAX_DEBUG

/*
 * HiSax PCMCIA card service modules
 */
#define CONFIG_HISAX_SEDLBAUER_CS_MODULE 1
#define CONFIG_HISAX_ELSA_CS_MODULE 1
#define CONFIG_HISAX_AVM_A1_CS_MODULE 1
#define CONFIG_HISAX_TELES_CS_MODULE 1

/*
 * HiSax sub driver modules
 */
#define CONFIG_HISAX_HFC4S8S_MODULE 1

/*
 * Active cards
 */
#define CONFIG_ISDN_DRV_ICN_MODULE 1
#define CONFIG_ISDN_DRV_SC_MODULE 1
#define CONFIG_ISDN_DRV_ACT2000_MODULE 1

/*
 * CAPI subsystem
 */
#define CONFIG_ISDN_CAPI_MODULE 1
#define CONFIG_ISDN_DRV_AVMB1_VERBOSE_REASON 1
#define CONFIG_ISDN_CAPI_MIDDLEWARE 1
#define CONFIG_ISDN_CAPI_CAPI20_MODULE 1
#define CONFIG_ISDN_CAPI_CAPIFS_BOOL 1
#define CONFIG_ISDN_CAPI_CAPIFS_MODULE 1
#define CONFIG_ISDN_CAPI_CAPIDRV_MODULE 1

/*
 * CAPI hardware drivers
 */

/*
 * Active AVM cards
 */
#define CONFIG_CAPI_AVM 1
#define CONFIG_ISDN_DRV_AVMB1_B1ISA_MODULE 1
#define CONFIG_ISDN_DRV_AVMB1_T1ISA_MODULE 1
#define CONFIG_ISDN_DRV_AVMB1_B1PCMCIA_MODULE 1
#define CONFIG_ISDN_DRV_AVMB1_AVM_CS_MODULE 1

/*
 * Active Eicon DIVA Server cards
 */
#define CONFIG_CAPI_EICON 1

/*
 * Telephony Support
 */
#define CONFIG_PHONE_MODULE 1
#define CONFIG_PHONE_IXJ_MODULE 1
#define CONFIG_PHONE_IXJ_PCMCIA_MODULE 1

/*
 * Input device support
 */
#define CONFIG_INPUT 1

/*
 * Userland interfaces
 */
#define CONFIG_INPUT_MOUSEDEV 1
#define CONFIG_INPUT_MOUSEDEV_PSAUX 1
#define CONFIG_INPUT_MOUSEDEV_SCREEN_X 1024
#define CONFIG_INPUT_MOUSEDEV_SCREEN_Y 768
#define CONFIG_INPUT_JOYDEV_MODULE 1
#undef CONFIG_INPUT_TSDEV
#define CONFIG_INPUT_EVDEV 1
#define CONFIG_INPUT_EVBUG_MODULE 1

/*
 * Input Device Drivers
 */
#define CONFIG_INPUT_KEYBOARD 1
#define CONFIG_KEYBOARD_ATKBD 1
#define CONFIG_KEYBOARD_SUNKBD_MODULE 1
#define CONFIG_KEYBOARD_LKKBD_MODULE 1
#define CONFIG_KEYBOARD_XTKBD_MODULE 1
#define CONFIG_KEYBOARD_NEWTON_MODULE 1
#define CONFIG_INPUT_MOUSE 1
#define CONFIG_MOUSE_PS2_MODULE 1
#define CONFIG_MOUSE_SERIAL_MODULE 1
#define CONFIG_MOUSE_INPORT_MODULE 1
#undef CONFIG_MOUSE_ATIXL
#define CONFIG_MOUSE_LOGIBM_MODULE 1
#define CONFIG_MOUSE_PC110PAD_MODULE 1
#define CONFIG_MOUSE_VSXXXAA_MODULE 1
#define CONFIG_INPUT_JOYSTICK 1
#define CONFIG_JOYSTICK_ANALOG_MODULE 1
#define CONFIG_JOYSTICK_A3D_MODULE 1
#define CONFIG_JOYSTICK_ADI_MODULE 1
#define CONFIG_JOYSTICK_COBRA_MODULE 1
#define CONFIG_JOYSTICK_GF2K_MODULE 1
#define CONFIG_JOYSTICK_GRIP_MODULE 1
#define CONFIG_JOYSTICK_GRIP_MP_MODULE 1
#define CONFIG_JOYSTICK_GUILLEMOT_MODULE 1
#define CONFIG_JOYSTICK_INTERACT_MODULE 1
#define CONFIG_JOYSTICK_SIDEWINDER_MODULE 1
#define CONFIG_JOYSTICK_TMDC_MODULE 1
#define CONFIG_JOYSTICK_IFORCE_MODULE 1
#define CONFIG_JOYSTICK_IFORCE_232 1
#define CONFIG_JOYSTICK_WARRIOR_MODULE 1
#define CONFIG_JOYSTICK_MAGELLAN_MODULE 1
#define CONFIG_JOYSTICK_SPACEORB_MODULE 1
#define CONFIG_JOYSTICK_SPACEBALL_MODULE 1
#define CONFIG_JOYSTICK_STINGER_MODULE 1
#define CONFIG_JOYSTICK_TWIDJOY_MODULE 1
#define CONFIG_JOYSTICK_DB9_MODULE 1
#define CONFIG_JOYSTICK_GAMECON_MODULE 1
#define CONFIG_JOYSTICK_TURBOGRAFX_MODULE 1
#define CONFIG_JOYSTICK_JOYDUMP_MODULE 1
#define CONFIG_INPUT_TOUCHSCREEN 1
#define CONFIG_TOUCHSCREEN_GUNZE_MODULE 1
#define CONFIG_TOUCHSCREEN_ELO_MODULE 1
#define CONFIG_TOUCHSCREEN_MTOUCH_MODULE 1
#define CONFIG_TOUCHSCREEN_MK712_MODULE 1
#define CONFIG_INPUT_MISC 1
#define CONFIG_INPUT_PCSPKR_MODULE 1
#define CONFIG_INPUT_UINPUT_MODULE 1

/*
 * Hardware I/O ports
 */
#define CONFIG_SERIO 1
#define CONFIG_SERIO_I8042 1
#define CONFIG_SERIO_SERPORT_MODULE 1
#define CONFIG_SERIO_PARKBD_MODULE 1
#define CONFIG_SERIO_LIBPS2 1
#define CONFIG_SERIO_RAW_MODULE 1
#define CONFIG_GAMEPORT_MODULE 1
#define CONFIG_GAMEPORT_NS558_MODULE 1
#define CONFIG_GAMEPORT_L4_MODULE 1

/*
 * Character devices
 */
#define CONFIG_VT 1
#define CONFIG_VT_CONSOLE 1
#define CONFIG_HW_CONSOLE 1
#define CONFIG_SERIAL_NONSTANDARD 1
#define CONFIG_COMPUTONE_MODULE 1
#define CONFIG_ROCKETPORT_MODULE 1
#define CONFIG_CYCLADES_MODULE 1
#undef CONFIG_CYZ_INTR
#define CONFIG_DIGIEPCA_MODULE 1
#define CONFIG_MOXA_INTELLIO_MODULE 1
#define CONFIG_MOXA_SMARTIO_MODULE 1
#undef CONFIG_ISI
#define CONFIG_SYNCLINKMP_MODULE 1
#define CONFIG_N_HDLC_MODULE 1
#define CONFIG_RISCOM8_MODULE 1
#define CONFIG_SPECIALIX_MODULE 1
#undef CONFIG_SPECIALIX_RTSCTS
#undef CONFIG_SX
#undef CONFIG_RIO
#define CONFIG_STALDRV 1
#define CONFIG_STALLION_MODULE 1
#define CONFIG_ISTALLION_MODULE 1

/*
 * Serial drivers
 */
#define CONFIG_SERIAL_8250 1
#define CONFIG_SERIAL_8250_CONSOLE 1
#define CONFIG_SERIAL_8250_CS_MODULE 1
#define CONFIG_SERIAL_8250_NR_UARTS 48
#define CONFIG_SERIAL_8250_EXTENDED 1
#define CONFIG_SERIAL_8250_MANY_PORTS 1
#define CONFIG_SERIAL_8250_SHARE_IRQ 1
#undef CONFIG_SERIAL_8250_DETECT_IRQ
#define CONFIG_SERIAL_8250_RSA 1
#define CONFIG_SERIAL_8250_FOURPORT_MODULE 1
#define CONFIG_SERIAL_8250_ACCENT_MODULE 1
#define CONFIG_SERIAL_8250_BOCA_MODULE 1
#define CONFIG_SERIAL_8250_HUB6_MODULE 1

/*
 * Non-8250 serial port support
 */
#undef CONFIG_SERIAL_IP22_ZILOG
#define CONFIG_SERIAL_CORE 1
#define CONFIG_SERIAL_CORE_CONSOLE 1
#define CONFIG_UNIX98_PTYS 1
#define CONFIG_LEGACY_PTYS 1
#define CONFIG_LEGACY_PTY_COUNT 256
#define CONFIG_PRINTER_MODULE 1
#undef CONFIG_LP_CONSOLE
#define CONFIG_PPDEV_MODULE 1
#undef CONFIG_TIPAR

/*
 * IPMI
 */
#define CONFIG_IPMI_HANDLER_MODULE 1
#undef CONFIG_IPMI_PANIC_EVENT
#define CONFIG_IPMI_DEVICE_INTERFACE_MODULE 1
#define CONFIG_IPMI_SI_MODULE 1
#define CONFIG_IPMI_WATCHDOG_MODULE 1
#define CONFIG_IPMI_POWEROFF_MODULE 1

/*
 * Watchdog Cards
 */
#define CONFIG_WATCHDOG 1
#undef CONFIG_WATCHDOG_NOWAYOUT

/*
 * Watchdog Device Drivers
 */
#define CONFIG_SOFT_WATCHDOG_MODULE 1
#undef CONFIG_INDYDOG

/*
 * ISA-based Watchdog Cards
 */
#define CONFIG_PCWATCHDOG_MODULE 1
#define CONFIG_MIXCOMWD_MODULE 1
#define CONFIG_WDT_MODULE 1
#undef CONFIG_WDT_501
#undef CONFIG_RTC
#undef CONFIG_SGI_DS1286
#undef CONFIG_GEN_RTC
#define CONFIG_DTLK_MODULE 1
#define CONFIG_R3964_MODULE 1

/*
 * Ftape, the floppy tape device driver
 */

/*
 * PCMCIA character devices
 */
#define CONFIG_SYNCLINK_CS_MODULE 1
#define CONFIG_CARDMAN_4000_MODULE 1
#define CONFIG_CARDMAN_4040_MODULE 1
#define CONFIG_RAW_DRIVER_MODULE 1
#define CONFIG_MAX_RAW_DEVS 256

/*
 * TPM devices
 */
#define CONFIG_TCG_TPM_MODULE 1
#define CONFIG_TCG_NSC_MODULE 1
#define CONFIG_TCG_ATMEL_MODULE 1
#define CONFIG_TELCLOCK_MODULE 1

/*
 * I2C support
 */
#define CONFIG_I2C 1
#define CONFIG_I2C_CHARDEV_MODULE 1

/*
 * I2C Algorithms
 */
#define CONFIG_I2C_ALGOBIT_MODULE 1
#define CONFIG_I2C_ALGOPCF_MODULE 1
#define CONFIG_I2C_ALGOPCA_MODULE 1
#undef CONFIG_I2C_ALGO_SGI

/*
 * I2C Hardware Bus support
 */
#undef CONFIG_I2C_ELEKTOR
#define CONFIG_I2C_ISA_MODULE 1
#define CONFIG_I2C_PARPORT_MODULE 1
#define CONFIG_I2C_PARPORT_LIGHT_MODULE 1
#define CONFIG_I2C_STUB_MODULE 1
#define CONFIG_I2C_PCA_ISA_MODULE 1

/*
 * Miscellaneous I2C Chip support
 */
#undef CONFIG_SENSORS_DS1337
#undef CONFIG_SENSORS_DS1374
#undef CONFIG_SENSORS_EEPROM
#undef CONFIG_SENSORS_PCF8574
#undef CONFIG_SENSORS_PCA9539
#define CONFIG_SENSORS_PCF8591_MODULE 1
#undef CONFIG_SENSORS_RTC8564
#undef CONFIG_SENSORS_MAX6875
#undef CONFIG_RTC_X1205_I2C
#undef CONFIG_I2C_DEBUG_CORE
#undef CONFIG_I2C_DEBUG_ALGO
#undef CONFIG_I2C_DEBUG_BUS
#undef CONFIG_I2C_DEBUG_CHIP

/*
 * Dallas's 1-wire bus
 */
#define CONFIG_W1_MODULE 1
#undef CONFIG_W1_THERM
#undef CONFIG_W1_SMEM
#undef CONFIG_W1_DS2433

/*
 * Hardware Monitoring support
 */
#define CONFIG_HWMON 1
#define CONFIG_HWMON_VID_MODULE 1
#define CONFIG_SENSORS_ADM1021_MODULE 1
#define CONFIG_SENSORS_ADM1025_MODULE 1
#define CONFIG_SENSORS_ADM1026_MODULE 1
#define CONFIG_SENSORS_ADM1031_MODULE 1
#define CONFIG_SENSORS_ADM9240_MODULE 1
#define CONFIG_SENSORS_ASB100_MODULE 1
#define CONFIG_SENSORS_ATXP1_MODULE 1
#define CONFIG_SENSORS_DS1621_MODULE 1
#undef CONFIG_SENSORS_FSCHER
#undef CONFIG_SENSORS_FSCPOS
#define CONFIG_SENSORS_GL518SM_MODULE 1
#define CONFIG_SENSORS_GL520SM_MODULE 1
#define CONFIG_SENSORS_IT87_MODULE 1
#define CONFIG_SENSORS_LM63_MODULE 1
#define CONFIG_SENSORS_LM75_MODULE 1
#define CONFIG_SENSORS_LM77_MODULE 1
#define CONFIG_SENSORS_LM78_MODULE 1
#define CONFIG_SENSORS_LM80_MODULE 1
#define CONFIG_SENSORS_LM83_MODULE 1
#define CONFIG_SENSORS_LM85_MODULE 1
#define CONFIG_SENSORS_LM87_MODULE 1
#define CONFIG_SENSORS_LM90_MODULE 1
#define CONFIG_SENSORS_LM92_MODULE 1
#define CONFIG_SENSORS_MAX1619_MODULE 1
#define CONFIG_SENSORS_PC87360_MODULE 1
#define CONFIG_SENSORS_SMSC47M1_MODULE 1
#define CONFIG_SENSORS_SMSC47B397_MODULE 1
#define CONFIG_SENSORS_W83781D_MODULE 1
#define CONFIG_SENSORS_W83792D_MODULE 1
#define CONFIG_SENSORS_W83L785TS_MODULE 1
#define CONFIG_SENSORS_W83627HF_MODULE 1
#define CONFIG_SENSORS_W83627EHF_MODULE 1
#undef CONFIG_HWMON_DEBUG_CHIP

/*
 * Misc devices
 */

/*
 * Multimedia Capabilities Port drivers
 */

/*
 * Multimedia devices
 */
#define CONFIG_VIDEO_DEV_MODULE 1

/*
 * Video For Linux
 */

/*
 * Video Adapters
 */
#define CONFIG_VIDEO_PMS_MODULE 1
#define CONFIG_VIDEO_BWQCAM_MODULE 1
#define CONFIG_VIDEO_CQCAM_MODULE 1
#define CONFIG_VIDEO_W9966_MODULE 1
#define CONFIG_VIDEO_CPIA_MODULE 1
#define CONFIG_VIDEO_CPIA_PP_MODULE 1
#define CONFIG_VIDEO_SAA5246A_MODULE 1
#define CONFIG_VIDEO_SAA5249_MODULE 1
#undef CONFIG_TUNER_3036
#undef CONFIG_VIDEO_VINO
#define CONFIG_VIDEO_OVCAMCHIP_MODULE 1
#undef CONFIG_VIDEO_AUDIO_DECODER
#undef CONFIG_VIDEO_DECODER

/*
 * Radio Adapters
 */
#define CONFIG_RADIO_CADET_MODULE 1
#define CONFIG_RADIO_RTRACK_MODULE 1
#define CONFIG_RADIO_RTRACK2_MODULE 1
#define CONFIG_RADIO_AZTECH_MODULE 1
#define CONFIG_RADIO_GEMTEK_MODULE 1
#define CONFIG_RADIO_MAESTRO_MODULE 1
#define CONFIG_RADIO_SF16FMI_MODULE 1
#define CONFIG_RADIO_SF16FMR2_MODULE 1
#define CONFIG_RADIO_TERRATEC_MODULE 1
#define CONFIG_RADIO_TRUST_MODULE 1
#define CONFIG_RADIO_TYPHOON_MODULE 1
#undef CONFIG_RADIO_TYPHOON_PROC_FS
#define CONFIG_RADIO_ZOLTRIX_MODULE 1

/*
 * Digital Video Broadcasting Devices
 */
#undef CONFIG_DVB

/*
 * Graphics support
 */
#define CONFIG_FB 1
#define CONFIG_FB_CFB_FILLRECT_MODULE 1
#define CONFIG_FB_CFB_COPYAREA_MODULE 1
#define CONFIG_FB_CFB_IMAGEBLIT_MODULE 1
#undef CONFIG_FB_MACMODES
#define CONFIG_FB_MODE_HELPERS 1
#define CONFIG_FB_TILEBLITTING 1
#define CONFIG_FB_S1D13XXX_MODULE 1
#undef CONFIG_FB_VIRTUAL

/*
 * Console display driver support
 */
#define CONFIG_VGA_CONSOLE 1
#define CONFIG_MDA_CONSOLE_MODULE 1
#undef CONFIG_SGI_NEWPORT_CONSOLE
#define CONFIG_DUMMY_CONSOLE 1
#define CONFIG_FRAMEBUFFER_CONSOLE_MODULE 1
#undef CONFIG_FRAMEBUFFER_CONSOLE_ROTATION
#undef CONFIG_FONTS
#define CONFIG_FONT_8x8 1
#define CONFIG_FONT_8x16 1

/*
 * Logo configuration
 */
#undef CONFIG_LOGO
#define CONFIG_BACKLIGHT_LCD_SUPPORT 1
#define CONFIG_BACKLIGHT_CLASS_DEVICE 1
#define CONFIG_BACKLIGHT_DEVICE 1
#define CONFIG_LCD_CLASS_DEVICE_MODULE 1
#define CONFIG_LCD_DEVICE 1

/*
 * Sound
 */
#define CONFIG_SOUND_MODULE 1

/*
 * Advanced Linux Sound Architecture
 */
#define CONFIG_SND_MODULE 1
#define CONFIG_SND_TIMER_MODULE 1
#define CONFIG_SND_PCM_MODULE 1
#define CONFIG_SND_HWDEP_MODULE 1
#define CONFIG_SND_RAWMIDI_MODULE 1
#define CONFIG_SND_SEQUENCER_MODULE 1
#define CONFIG_SND_SEQ_DUMMY_MODULE 1
#define CONFIG_SND_OSSEMUL 1
#define CONFIG_SND_MIXER_OSS_MODULE 1
#define CONFIG_SND_PCM_OSS_MODULE 1
#define CONFIG_SND_SEQUENCER_OSS 1
#undef CONFIG_SND_VERBOSE_PRINTK
#undef CONFIG_SND_DEBUG
#define CONFIG_SND_GENERIC_DRIVER 1

/*
 * Generic devices
 */
#define CONFIG_SND_MPU401_UART_MODULE 1
#define CONFIG_SND_VX_LIB_MODULE 1
#define CONFIG_SND_DUMMY_MODULE 1
#define CONFIG_SND_VIRMIDI_MODULE 1
#define CONFIG_SND_MTPAV_MODULE 1
#define CONFIG_SND_SERIAL_U16550_MODULE 1
#define CONFIG_SND_MPU401_MODULE 1

/*
 * ALSA MIPS devices
 */

/*
 * PCMCIA devices
 */
#define CONFIG_SND_VXPOCKET_MODULE 1
#define CONFIG_SND_PDAUDIOCF_MODULE 1

/*
 * Open Sound System
 */
#define CONFIG_SOUND_PRIME_MODULE 1
#undef CONFIG_OBSOLETE_OSS_DRIVER
#undef CONFIG_SOUND_HAL2
#define CONFIG_SOUND_MSNDCLAS_MODULE 1
#define CONFIG_MSNDCLAS_INIT_FILE "/etc/sound/msndinit.bin"
#define CONFIG_MSNDCLAS_PERM_FILE "/etc/sound/msndperm.bin"
#define CONFIG_SOUND_MSNDPIN_MODULE 1
#define CONFIG_MSNDPIN_INIT_FILE "/etc/sound/pndspini.bin"
#define CONFIG_MSNDPIN_PERM_FILE "/etc/sound/pndsperm.bin"
#undef CONFIG_SOUND_TVMIXER

/*
 * USB support
 */
#undef CONFIG_USB_ARCH_HAS_HCD
#undef CONFIG_USB_ARCH_HAS_OHCI
#undef CONFIG_USB_ARCH_HAS_EHCI

/*
 * NOTE: USB_STORAGE enables SCSI, and 'SCSI disk support'
 */

/*
 * USB Gadget Support
 */
#define CONFIG_USB_GADGET_MODULE 1
#undef CONFIG_USB_GADGET_DEBUG_FILES
#undef CONFIG_USB_GADGET_AR9130
#undef CONFIG_USB_GADGET_NET2280
#undef CONFIG_USB_GADGET_PXA2XX
#undef CONFIG_USB_GADGET_GOKU
#undef CONFIG_USB_GADGET_LH7A40X
#undef CONFIG_USB_GADGET_OMAP
#undef CONFIG_USB_GADGET_DUMMY_HCD
#undef CONFIG_USB_GADGET_DUALSPEED

/*
 * MMC/SD Card support
 */
#define CONFIG_MMC 1
#undef CONFIG_MMC_DEBUG
#define CONFIG_MMC_BLOCK_MODULE 1

/*
 * InfiniBand support
 */

/*
 * SN Devices
 */

/*
 * File systems
 */
#define CONFIG_EXT2_FS 1
#define CONFIG_EXT2_FS_XATTR 1
#define CONFIG_EXT2_FS_POSIX_ACL 1
#define CONFIG_EXT2_FS_SECURITY 1
#undef CONFIG_EXT2_FS_XIP
#define CONFIG_EXT3_FS 1
#define CONFIG_EXT3_FS_XATTR 1
#define CONFIG_EXT3_FS_POSIX_ACL 1
#define CONFIG_EXT3_FS_SECURITY 1
#define CONFIG_JBD 1
#undef CONFIG_JBD_DEBUG
#define CONFIG_FS_MBCACHE 1
#define CONFIG_REISERFS_FS_MODULE 1
#undef CONFIG_REISERFS_CHECK
#undef CONFIG_REISERFS_PROC_INFO
#define CONFIG_REISERFS_FS_XATTR 1
#define CONFIG_REISERFS_FS_POSIX_ACL 1
#define CONFIG_REISERFS_FS_SECURITY 1
#define CONFIG_JFS_FS_MODULE 1
#define CONFIG_JFS_POSIX_ACL 1
#define CONFIG_JFS_SECURITY 1
#undef CONFIG_JFS_DEBUG
#define CONFIG_JFS_STATISTICS 1
#define CONFIG_FS_POSIX_ACL 1
#define CONFIG_XFS_FS_MODULE 1
#define CONFIG_XFS_EXPORT 1
#define CONFIG_XFS_QUOTA 1
#undef CONFIG_XFS_SECURITY
#define CONFIG_XFS_POSIX_ACL 1
#define CONFIG_XFS_RT 1
#define CONFIG_MINIX_FS_MODULE 1
#define CONFIG_ROMFS_FS_MODULE 1
#define CONFIG_INOTIFY 1
#define CONFIG_QUOTA 1
#define CONFIG_QFMT_V1_MODULE 1
#define CONFIG_QFMT_V2_MODULE 1
#define CONFIG_QUOTACTL 1
#define CONFIG_DNOTIFY 1
#define CONFIG_AUTOFS_FS_MODULE 1
#define CONFIG_AUTOFS4_FS_MODULE 1
#define CONFIG_FUSE_FS 1

/*
 * CD-ROM/DVD Filesystems
 */
#define CONFIG_ISO9660_FS_MODULE 1
#define CONFIG_JOLIET 1
#define CONFIG_ZISOFS 1
#define CONFIG_ZISOFS_FS_MODULE 1
#define CONFIG_UDF_FS_MODULE 1
#define CONFIG_UDF_NLS 1

/*
 * DOS/FAT/NT Filesystems
 */
#define CONFIG_FAT_FS_MODULE 1
#define CONFIG_MSDOS_FS_MODULE 1
#define CONFIG_VFAT_FS_MODULE 1
#define CONFIG_FAT_DEFAULT_CODEPAGE 437
#define CONFIG_FAT_DEFAULT_IOCHARSET "iso8859-1"
#define CONFIG_NTFS_FS_MODULE 1
#undef CONFIG_NTFS_DEBUG
#undef CONFIG_NTFS_RW

/*
 * Pseudo filesystems
 */
#define CONFIG_PROC_FS 1
#define CONFIG_PROC_KCORE 1
#define CONFIG_SYSFS 1
#define CONFIG_TMPFS 1
#undef CONFIG_HUGETLB_PAGE
#define CONFIG_RAMFS 1
#undef CONFIG_RELAYFS_FS

/*
 * Miscellaneous filesystems
 */
#define CONFIG_ADFS_FS_MODULE 1
#undef CONFIG_ADFS_FS_RW
#define CONFIG_AFFS_FS_MODULE 1
#define CONFIG_HFS_FS_MODULE 1
#define CONFIG_HFSPLUS_FS_MODULE 1
#define CONFIG_BEFS_FS_MODULE 1
#undef CONFIG_BEFS_DEBUG
#define CONFIG_BFS_FS_MODULE 1
#define CONFIG_EFS_FS_MODULE 1
#undef CONFIG_JFFS_FS
#define CONFIG_JFFS2_FS_MODULE 1
#define CONFIG_JFFS2_FS_DEBUG 0
#define CONFIG_JFFS2_FS_WRITEBUFFER 1
#undef CONFIG_JFFS2_SUMMARY
#define CONFIG_JFFS2_COMPRESSION_OPTIONS 1
#define CONFIG_JFFS2_ZLIB 1
#define CONFIG_JFFS2_RTIME 1
#undef CONFIG_JFFS2_RUBIN
#undef CONFIG_JFFS2_CMODE_NONE
#define CONFIG_JFFS2_CMODE_PRIORITY 1
#undef CONFIG_JFFS2_CMODE_SIZE
#define CONFIG_CRAMFS_MODULE 1
#define CONFIG_SQUASHFS_MODULE 1
#undef CONFIG_SQUASHFS_EMBEDDED
#define CONFIG_SQUASHFS_FRAGMENT_CACHE_SIZE 3
#define CONFIG_VXFS_FS_MODULE 1
#define CONFIG_HPFS_FS_MODULE 1
#define CONFIG_QNX4FS_FS_MODULE 1
#define CONFIG_SYSV_FS_MODULE 1
#define CONFIG_UFS_FS_MODULE 1
#undef CONFIG_UFS_FS_WRITE

/*
 * Network File Systems
 */
#define CONFIG_NFS_FS_MODULE 1
#define CONFIG_NFS_V3 1
#define CONFIG_NFS_V3_ACL 1
#define CONFIG_NFS_V4 1
#undef CONFIG_NFS_DIRECTIO
#define CONFIG_NFSD_MODULE 1
#define CONFIG_NFSD_V2_ACL 1
#define CONFIG_NFSD_V3 1
#define CONFIG_NFSD_V3_ACL 1
#define CONFIG_NFSD_V4 1
#define CONFIG_NFSD_TCP 1
#define CONFIG_LOCKD_MODULE 1
#define CONFIG_LOCKD_V4 1
#define CONFIG_EXPORTFS_MODULE 1
#define CONFIG_NFS_ACL_SUPPORT_MODULE 1
#define CONFIG_NFS_COMMON 1
#define CONFIG_SUNRPC_MODULE 1
#define CONFIG_SUNRPC_GSS_MODULE 1
#define CONFIG_RPCSEC_GSS_KRB5_MODULE 1
#define CONFIG_RPCSEC_GSS_SPKM3_MODULE 1
#define CONFIG_SMB_FS_MODULE 1
#undef CONFIG_SMB_NLS_DEFAULT
#define CONFIG_CIFS_MODULE 1
#undef CONFIG_CIFS_STATS
#define CONFIG_CIFS_XATTR 1
#define CONFIG_CIFS_POSIX 1
#define CONFIG_CIFS_EXPERIMENTAL 1
#define CONFIG_CIFS_UPCALL 1
#define CONFIG_NCP_FS_MODULE 1
#define CONFIG_NCPFS_PACKET_SIGNING 1
#define CONFIG_NCPFS_IOCTL_LOCKING 1
#define CONFIG_NCPFS_STRONG 1
#define CONFIG_NCPFS_NFS_NS 1
#define CONFIG_NCPFS_OS2_NS 1
#undef CONFIG_NCPFS_SMALLDOS
#define CONFIG_NCPFS_NLS 1
#define CONFIG_NCPFS_EXTRAS 1
#define CONFIG_CODA_FS_MODULE 1
#undef CONFIG_CODA_FS_OLD_API
#define CONFIG_AFS_FS_MODULE 1
#define CONFIG_RXRPC_MODULE 1
#define CONFIG_9P_FS_MODULE 1

/*
 * Partition Types
 */
#define CONFIG_PARTITION_ADVANCED 1
#define CONFIG_ACORN_PARTITION 1
#undef CONFIG_ACORN_PARTITION_CUMANA
#undef CONFIG_ACORN_PARTITION_EESOX
#define CONFIG_ACORN_PARTITION_ICS 1
#undef CONFIG_ACORN_PARTITION_ADFS
#undef CONFIG_ACORN_PARTITION_POWERTEC
#define CONFIG_ACORN_PARTITION_RISCIX 1
#define CONFIG_OSF_PARTITION 1
#define CONFIG_AMIGA_PARTITION 1
#define CONFIG_ATARI_PARTITION 1
#define CONFIG_MAC_PARTITION 1
#define CONFIG_MSDOS_PARTITION 1
#define CONFIG_BSD_DISKLABEL 1
#define CONFIG_MINIX_SUBPARTITION 1
#define CONFIG_SOLARIS_X86_PARTITION 1
#define CONFIG_UNIXWARE_DISKLABEL 1
#define CONFIG_LDM_PARTITION 1
#undef CONFIG_LDM_DEBUG
#define CONFIG_SGI_PARTITION 1
#define CONFIG_ULTRIX_PARTITION 1
#define CONFIG_SUN_PARTITION 1
#define CONFIG_EFI_PARTITION 1

/*
 * Native Language Support
 */
#define CONFIG_NLS 1
#define CONFIG_NLS_DEFAULT "cp437"
#define CONFIG_NLS_CODEPAGE_437_MODULE 1
#define CONFIG_NLS_CODEPAGE_737_MODULE 1
#define CONFIG_NLS_CODEPAGE_775_MODULE 1
#define CONFIG_NLS_CODEPAGE_850_MODULE 1
#define CONFIG_NLS_CODEPAGE_852_MODULE 1
#define CONFIG_NLS_CODEPAGE_855_MODULE 1
#define CONFIG_NLS_CODEPAGE_857_MODULE 1
#define CONFIG_NLS_CODEPAGE_860_MODULE 1
#define CONFIG_NLS_CODEPAGE_861_MODULE 1
#define CONFIG_NLS_CODEPAGE_862_MODULE 1
#define CONFIG_NLS_CODEPAGE_863_MODULE 1
#define CONFIG_NLS_CODEPAGE_864_MODULE 1
#define CONFIG_NLS_CODEPAGE_865_MODULE 1
#define CONFIG_NLS_CODEPAGE_866_MODULE 1
#define CONFIG_NLS_CODEPAGE_869_MODULE 1
#define CONFIG_NLS_CODEPAGE_936_MODULE 1
#define CONFIG_NLS_CODEPAGE_950_MODULE 1
#define CONFIG_NLS_CODEPAGE_932_MODULE 1
#define CONFIG_NLS_CODEPAGE_949_MODULE 1
#define CONFIG_NLS_CODEPAGE_874_MODULE 1
#define CONFIG_NLS_ISO8859_8_MODULE 1
#define CONFIG_NLS_CODEPAGE_1250_MODULE 1
#define CONFIG_NLS_CODEPAGE_1251_MODULE 1
#define CONFIG_NLS_ASCII_MODULE 1
#define CONFIG_NLS_ISO8859_1_MODULE 1
#define CONFIG_NLS_ISO8859_2_MODULE 1
#define CONFIG_NLS_ISO8859_3_MODULE 1
#define CONFIG_NLS_ISO8859_4_MODULE 1
#define CONFIG_NLS_ISO8859_5_MODULE 1
#define CONFIG_NLS_ISO8859_6_MODULE 1
#define CONFIG_NLS_ISO8859_7_MODULE 1
#define CONFIG_NLS_ISO8859_9_MODULE 1
#define CONFIG_NLS_ISO8859_13_MODULE 1
#define CONFIG_NLS_ISO8859_14_MODULE 1
#define CONFIG_NLS_ISO8859_15_MODULE 1
#define CONFIG_NLS_KOI8_R_MODULE 1
#define CONFIG_NLS_KOI8_U_MODULE 1
#define CONFIG_NLS_UTF8_MODULE 1

/*
 * Profiling support
 */
#define CONFIG_PROFILING 1
#define CONFIG_OPROFILE_MODULE 1

/*
 * Kernel hacking
 */
#define CONFIG_PRINTK_TIME 1
#define CONFIG_DEBUG_KERNEL 1
#define CONFIG_MAGIC_SYSRQ 1
#define CONFIG_LOG_BUF_SHIFT 17
#define CONFIG_DETECT_SOFTLOCKUP 1
#define CONFIG_SCHEDSTATS 1
#undef CONFIG_DEBUG_SLAB
#undef CONFIG_DEBUG_SPINLOCK
#undef CONFIG_DEBUG_SPINLOCK_SLEEP
#undef CONFIG_DEBUG_KOBJECT
#define CONFIG_DEBUG_INFO 1
#define CONFIG_DEBUG_FS 1
#undef CONFIG_DEBUG_VM
#undef CONFIG_RCU_TORTURE_TEST
#undef CONFIG_CROSSCOMPILE
#define CONFIG_CMDLINE ""
#undef CONFIG_DEBUG_STACK_USAGE
#define CONFIG_KGDB 1
#undef CONFIG_GDB_CONSOLE
#undef CONFIG_RUNTIME_DEBUG
#undef CONFIG_MIPS_UNCACHED

/*
 * Security options
 */
#define CONFIG_KEYS 1
#undef CONFIG_KEYS_DEBUG_PROC_KEYS
#define CONFIG_SECURITY 1
#define CONFIG_SECURITY_NETWORK 1
#undef CONFIG_SECURITY_CAPABILITIES
#undef CONFIG_SECURITY_SECLVL
#define CONFIG_SECURITY_SELINUX 1
#define CONFIG_SECURITY_SELINUX_BOOTPARAM 1
#define CONFIG_SECURITY_SELINUX_BOOTPARAM_VALUE 0
#define CONFIG_SECURITY_SELINUX_DISABLE 1
#define CONFIG_SECURITY_SELINUX_DEVELOP 1
#define CONFIG_SECURITY_SELINUX_AVC_STATS 1
#define CONFIG_SECURITY_SELINUX_CHECKREQPROT_VALUE 1

/*
 * Cryptographic options
 */
#define CONFIG_CRYPTO 1
#define CONFIG_CRYPTO_HMAC 1
#define CONFIG_CRYPTO_NULL_MODULE 1
#define CONFIG_CRYPTO_MD4_MODULE 1
#define CONFIG_CRYPTO_MD5 1
#define CONFIG_CRYPTO_SHA1_MODULE 1
#define CONFIG_CRYPTO_SHA256_MODULE 1
#define CONFIG_CRYPTO_SHA512_MODULE 1
#define CONFIG_CRYPTO_WP512_MODULE 1
#define CONFIG_CRYPTO_TGR192_MODULE 1
#define CONFIG_CRYPTO_DES_MODULE 1
#define CONFIG_CRYPTO_BLOWFISH_MODULE 1
#define CONFIG_CRYPTO_TWOFISH_MODULE 1
#define CONFIG_CRYPTO_SERPENT_MODULE 1
#define CONFIG_CRYPTO_AES_MODULE 1
#define CONFIG_CRYPTO_CAST5_MODULE 1
#define CONFIG_CRYPTO_CAST6_MODULE 1
#define CONFIG_CRYPTO_TEA_MODULE 1
#define CONFIG_CRYPTO_ARC4_MODULE 1
#define CONFIG_CRYPTO_KHAZAD_MODULE 1
#define CONFIG_CRYPTO_ANUBIS_MODULE 1
#define CONFIG_CRYPTO_DEFLATE_MODULE 1
#define CONFIG_CRYPTO_MICHAEL_MIC_MODULE 1
#define CONFIG_CRYPTO_CRC32C_MODULE 1
#define CONFIG_CRYPTO_TEST_MODULE 1

/*
 * Hardware crypto devices
 */

/*
 * Library routines
 */
#define CONFIG_CRC_CCITT_MODULE 1
#define CONFIG_CRC16 1
#define CONFIG_CRC32 1
#define CONFIG_LIBCRC32C_MODULE 1
#define CONFIG_ZLIB_INFLATE_MODULE 1
#define CONFIG_ZLIB_DEFLATE_MODULE 1
#define CONFIG_REED_SOLOMON_MODULE 1
#define CONFIG_REED_SOLOMON_DEC16 1
#define CONFIG_TEXTSEARCH 1
#define CONFIG_TEXTSEARCH_KMP_MODULE 1
#define CONFIG_TEXTSEARCH_BM_MODULE 1
#define CONFIG_TEXTSEARCH_FSM_MODULE 1
