# $Id: //depot/sw/releases/7.3_AP/linux/kernels/mips-linux-2.6.15/arch/sparc/prom/Makefile#1 $
# Makefile for the Sun Boot PROM interface library under
# Linux.
#

lib-y := bootstr.o devmap.o devops.o init.o memory.o misc.o mp.o \
	 palloc.o ranges.o segment.o console.o printf.o tree.o

lib-$(CONFIG_SUN4) += sun4prom.o
